name: Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.3

    - name: Install
      run: |
        yarn install

    - name: Build
      env:
        CI: true
      run: |
        yarn run start
